[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
wallpaper_control = {path = "../../packages/wallpaper_control"}
config = {path = "../../packages/config"}

[[bin]]
name = "wallpapercl_gui"
path = "src/main.rs"
